### ISSUE TITLE
When commercials start or end the channels freeze

### ISSUE THREAD

**Issue by emkowale** [mclenburg/plutoTV-tvheadend#11]
Hi,

     I'm a SMATV guy from back in the day and a 30+ year computer scientist.  Linux and tvheadend are my jam so I was happy to stumble upon your work. Thanks for this! When commercials start or end the PlutoTv channels freeze. The commercials are a bunch of liberal crap anyway. I'd like to know if this is a Kodi thing or it is related to tvheadend or possibly PlutoTV!  Kinda wondering what the advantages are to using ffmpeg vs not. One thing is for sure, Kodi runs way better without a ton of plugins. That's why I prefer running this through tvheadend.

Thanks,
emkowale

**Comment by mclenburg** [comment]
Hi,
as far as I know, tvh will use ffmpeg to receive and transform any multi-playlist as delivered in plutoTV master.m3u8-file.
As a bug (or maybe a missing Feature) in ffmpeg, ffmpeg can't understand EXT-X-DISCONTINOUITY in playlist-file up to now, so the stream stucks, when this tag is reached in file, as it is at end of movie or when advertising starts.

In plutotv-localserver.pl I'm trying to remove these tags and following streams, which results in much less advertisings, but also in hanging at end of movie, as it will also start with new timestamps as DISCONTINUITY.

**Comment by emkowale** [comment]
Well this is a great package. More people should use tvheadend too.
