### ISSUE TITLE
m3u contents parsing failed

### ISSUE THREAD

**Issue by emkowale** [mclenburg/plutoTV-tvheadend#12]
I did notice another issue and this may lead to an improvement. Being in cable tv for 20 years I always had people ask "why do we have to pay for channels they didn't watch?" Now of course plutotv is free and the new question is "how do I remove channels from the lineup I don't want like language channels I do not understand?" My initial though was to remove them from the plutotv.m3u file that your awesome script generates. I did that and got "m3u contents parsing failed".  I'm sure I edited the file correctly.  Doubting my confidence I scrapped my plan of editing the file and I still get the error.  I also noticed an error/warning when I ran the script:

root@mediapi:/home/pi# perl /home/pi/plutotv-generate.pl
From 2021-05-18T19:59:27Z To 2021-05-28T19:59:27Z
WARNING: no url found for Sky News
Use of uninitialized value in index at /home/pi/plutotv-generate.pl line 143.
Use of uninitialized value in substr at /home/pi/plutotv-generate.pl line 143.
Use of uninitialized value in index at /home/pi/plutotv-generate.pl line 143.
Use of uninitialized value in substr at /home/pi/plutotv-generate.pl line 143.
Use of uninitialized value in index at /home/pi/plutotv-generate.pl line 143.
Use of uninitialized value in substr at /home/pi/plutotv-generate.pl line 143.
Ready
root@mediapi:/home/pi#

I have charter communications and use two HDhomeruns to feed tvheadend to the entire house. Just like plutotv I create an IPTV Automatic Network that points to the .m3u file.  I edit the charter.m3u file and cut out the crap like fake news cnn and MSDNC.  From there I scan the network m3u files and create muxes which I then scan to services and ultimately channels. I get the guide info from https://www.schedulesdirect.org/ for the charter channels and of course, your awesome software has a way to get the guide. I hope this helps someone. 

Any ideas?
Thanks,
Eric

**Comment by mclenburg** [comment]
Hi, first of all: tvheadend also offers the possibility to disable unwanted channels from the m3u. 
And now about the faulty m3u: unfortunately plutoTV is multi-regional, so it is not possible for me to recreate the error.
Please send me the faulty m3u and (if possible) the json file from http://api.pluto.tv/v2/channels .
Thanks.

**Comment by chewiebrian** [comment]
Hi, I am suffering from the same failure. In my case several channels works but others not. For example, VH1 Classics dont works but the Wipeout channel does work.

Here are my M3U contents and the response of the channels API.

[plutotv.m3u.txt](https://github.com/mclenburg/plutoTV-tvheadend/files/6515970/plutotv.m3u.txt)
[channels.txt](https://github.com/mclenburg/plutoTV-tvheadend/files/6515971/channels.txt)

**Comment by mclenburg** [comment]
channels.json and plutotv.m3u look good at first sight.
However, the m3u contains UTF-8 characters, which might be a problem. Please rename the file once to plutotv.m3u8 and use that.

**Comment by chewiebrian** [comment]
Thanks, it worked! I can't believe it was so easy ;)

**Comment by emkowale** [comment]
I think may have solved my issue too.
