### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Toei79** [mclenburg/plutoTV-tvheadend#13]
i follow all steps but i get something like out of memory when try to run channels on tvheadend

i run the script, and i get .m3u8 file with example 250 channels, and i get 250 .sh files with name of each channels on those

that give me an out of memory.

i get this kind of generate on m3u8

`pipe:///usr/bin/streamlink --stdout --quiet --twitch-disable-hosting --ringbuffer-size 8M --hds-segment-threads 2 --hls-segment-attempts 2 --hls-segment-key-uri "" --hls-segment-timeout 5 "http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5331d5fb753499095a00045a/master.m3u8?advertisingId=&appName=web&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=false&deviceId=0d89e5bb-f955-11eb-88cc-cde4f5d5135f&deviceLat=26.0276&deviceLon=-80.2528&deviceMake=Firefox&deviceModel=web&deviceType=web&deviceVersion=82.0&includeExtendedEvents=false&marketingRegion=US&sid=0ea66e34-f955-11eb-88cc-9c6d042ab5e5&sessionID=0ea66e34-f955-11eb-88cc-9c6d042ab5e5&userId=&serverSideAds=false&terminate=false&clientDeviceType=0&clientModelNumber=na&clientID=0d89e5bb-f955-11eb-88cc-cde4f5d5135f" 720,best `

![08-09-2021 (170030)](https://user-images.githubusercontent.com/79808610/128774214-3558c016-791c-43c9-a65d-2072f7f1c43d.jpg)

![08-09-2021 (170342)](https://user-images.githubusercontent.com/79808610/128774245-a08c2db2-4600-49ec-8298-ca3d367e43f0.jpg)

my main goal its record from pluto, using tivimate there some other places where playlist its available or can generate it but i cant record with those on tivimate.

**Comment by mclenburg** [comment]
Seems to be a streamlink-issue.
Try running with --useffmpeg instead.

**Comment by Toei79** [comment]
how can be instructions of ffmeg?

i guess i alreafy try i need check in home tonight

thanks
