### ISSUE TITLE
socat : Connection refused

### ISSUE THREAD

**Issue by emkowale** [mclenburg/plutoTV-tvheadend#14]
Hi,

When I run :

 cat plutotv-epg.xml | socat - UNIX-CONNECT:/var/lib/hts/.hts/tvheadend/epggrab/xmltv.sock

  I get this:

2021/09/21 12:53:06 socat[7562] E connect(5, AF=1 "/var/lib/hts/.hts/tvheadend/epggrab/xmltv.sock", 48): Connection refused

  Can you help?
  Thanks,
  Eric

**Comment by mclenburg** [comment]
This looks like tvheadend's XMLTV grabber is not activated.
For activating the grabber log in to tvheadends web-interface and enable the external XMLTV grabber at 
Configuration -> Channel/EPG -> EPG Grabber Modules

**Comment by emkowale** [comment]
It is enabled for sure.  I have even tried to disable and re-emable.

**Comment by emkowale** [comment]
Figured it out with your help.  In the grabber module interface I noticed that the Path: was different than the path in your example.  I replaced it and all is well!!
