### ISSUE TITLE
Error using m3u with streamlink

### ISSUE THREAD

**Issue by razametal** [mclenburg/plutoTV-tvheadend#15]
Hi,

Using the m3u8 list generated with: 

perl plutotv-generate.pl --createm3u --usestreamlink

I've the following error on the tvheadend log:

Nov  6 12:16:45 localhost tvheadend[3979035]: spawn: streamlink: error: unrecognized arguments: 720,best

Editing the m3u8 file and deleting the string 720,best does not solve the error and the mux is not being usable.

On the mux URL I have:

pipe:///usr/bin/streamlink --stdout --quiet --twitch-disable-hosting --ringbuffer-size 8M --hds-segment-threads 2 --hls-segment-attempts 2 --hls-segment-key-uri "" --hls-segment-timeout 5 "http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dcb62e63d4d8f0009f36881/master.m3u8?advertisingId=&appName=web&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=false&deviceId=9d2dd243-3f23-11ec-9360-f0575f0fab6a&deviceLat=-1.2160&deviceLon=-80.3827&deviceMake=Firefox&deviceModel=web&deviceType=web&deviceVersion=82.0&includeExtendedEvents=false&marketingRegion=VE&sid=a04d7d7f-3f23-11ec-9360-8c766c7f2f74&sessionID=a04d7d7f-3f23-11ec-9360-8c766c7f2f74&userId=&serverSideAds=false&terminate=false&clientDeviceType=0&clientModelNumber=na&clientID=9d2dd243-3f23-11ec-9360-f0575f0fab6a" 720,best

My streamlink version is: 

streamlink 2.4.0

**Comment by mclenburg** [comment]
I have adjusted the streamlink parameters. Please try again.

**Comment by razametal** [comment]
Hi @mclenburg thank you for the help.

Yes, is working now whitout errors:

tail -f /var/log/syslog | grep streaml
Nov 11 18:19:45 localhost tvheadend[427330]: spawn: Executing "/usr/local/bin/streamlink"
Nov 11 18:22:59 localhost tvheadend[427330]: spawn: Executing "/usr/local/bin/streamlink"
Nov 11 18:22:59 localhost tvheadend[427330]: spawn: Executing "/usr/local/bin/streamlink"
