### ISSUE TITLE
spawn: Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by emkowale** [mclenburg/plutoTV-tvheadend#19]
I love this software, but it think something changed with the new version of ffmpeg. I get:

spawn: Error splitting the argument list: Option not found

None of my muxes will convert to services. I'm running tvheadend on a Raspberry Pi 4 64 aarch64.

**Comment by mclenburg** [comment]
Hi, thx for using this scripts.
Are u using latest script-versions?
Which version of ffmpeg did u use?

**Comment by emkowale** [comment]
I was able to fix it. From what I could tell the new version of ffmpeg took out an argument. I edited your .pl and removed the -user-agent option and it worked.

Now if I could fix that freeze that happens when PlutoTv comes in and out of commercial. Was streamlink supposed to fix that?

**Comment by mclenburg** [comment]
Hi, latest version of streamlink plays fluently.
