### ISSUE TITLE
How do I import the epg file?

### ISSUE THREAD

**Issue by cfredericksen** [mclenburg/plutoTV-tvheadend#3]
I tried ./usr/bin/tv_grab_file against the generated epg file but it doesnt show in TVH. What format is the epg file?
plutotv-epg.xml  does contain guide data.

root@tvheadend-69446b786b-qpqp5:/# tail /config/plutotv-epg.xml 
<desc lang="de"><![CDATA[A bootlegger operating an illicit still on Fire Island hires a killer to protect the operation.]]></desc>
</programme>
<programme start="20200819063000000 +0000" stop="20200819070000 +0000" channel="Classic%20TV%20Drama">
<title lang="de"><![CDATA[Naked City - Not Rated]]></title>
<desc lang="de"><![CDATA[A poor Puerto Rican couple finds $10 and bets it on the numbers, winning $6,000.]]></desc>
</programme>

</tv>

**Comment by mclenburg** [comment]
As advised in sunsettrack4/zattoo_tvh: 
- Go to menu option "Configuration" > "Channel/EPG" > "EPG Grabber Modules" and enable "External: XMLTV"
- Go to menu option "Configuration" > "Channel/EPG" > "Channel" > "Map services" > "Map all services" and map the services
- Run the following command twice:
cat <pathtoepgfile> | socat - UNIX-CONNECT:/home/<user>/.hts/tvheadend/epggrab/xmltv.sock
