### ISSUE TITLE
Pass along my results

### ISSUE THREAD

**Issue by cfredericksen** [mclenburg/plutoTV-tvheadend#4]
I wanted to let you know how I made a recordings stable and now its working perfectly. 

I installed streamlink then pipe it to ffmpeg for all my muxes using your script.  
#!/bin/bash
streamlink --stdout --quiet --hds-segment-threads 3 "$1" best | ffmpeg -loglevel quiet -i pipe:0 -vcodec copy -acodec copy -mpegts_service_type advanced_codec_digital_hdtv -f mpegts pipe:1

Let me know if this is helpful.

**Comment by mclenburg** [comment]
Thx for ur work.
I've added usage of streamlink (without piping result to ffmpeg) to script.
It will use streamlink in bashfile, if it's found in path.

**Comment by ErAzOr2k** [comment]
@cfredericksen thank you for sharing your command. This is the only way to get a flawless stream
