### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by dinki** [mclenburg/plutoTV-tvheadend#5]
First, thanks for creating this.  I'm looking for a way to record PlutoTV and this seems to be a great option.

I've installed your script on my Open Media Vault Linux server and I can run the script just fine.  I'm using

`plutotv-generate.pl --createm3u --usebash
`
I've tested the output url in VLC and it plays fine.

In full disclosure, I've run TVHeadend long ago but don't have a whole lot of experience with it.  I am running TVH in a Docker container.  I've managed to import the m3u in by going to Config->DVB Inputs->Networks and adding URL file:///config/pluto/plutotv.m3u   .  I can then go to Muxes and see all the PTV channels but all Scan Results show Failed.  I thought that this may be a pathing issue as I am running in Docker so I changed all file links to point to where I am storing the files in the container (/config/pluto/plutotv.m3u).  Is this what I should be doing?

I am also at a loss on how to configure the EPG import.  Could you possibly explain this or point me to a good reference?

Lastly, should I be using streamlink?  If so, could you possibly tell me how I should install this?  FFMPEG is familiar to me from other projects so it's fine if the difference is not notable.

Thanks for the help.

**Comment by dinki** [comment]
Also, I'm noticing these errors when I run the script:

$ ./plutotv-generate.pl --createm3u --usebash
From 2020-09-05T19:36:07Z To 2020-09-15T19:36:07Z
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 94.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 95.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 96.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 97.
Use of uninitialized value $url in substitution (s///) at ./plutotv-generate.pl line 108.
Use of uninitialized value $url in concatenation (.) or string at ./plutotv-generate.pl line 117.
Use of uninitialized value in index at ./plutotv-generate.pl line 103.
Use of uninitialized value in substr at ./plutotv-generate.pl line 103.
Use of uninitialized value in index at ./plutotv-generate.pl line 103.
Use of uninitialized value in substr at ./plutotv-generate.pl line 103.
Use of uninitialized value in index at ./plutotv-generate.pl line 103.
Use of uninitialized value in substr at ./plutotv-generate.pl line 103.
Ready


Also note that no matter which switch I use I always get streamlink options.  I am going to modify this to force ffmpeg options as ffmpeg is the only option installed in the Docker container.  Also noticed a port of 8282.  I'm using 9981/9982 as per the Docker container option recommendations.  I guess I'll need to modify your script to match 8282 to 9982?

*EDIT*
So I set streamlink variable to an empty string and it now outputs the ffmpeg arguments in the .sh file.  I opened a shell in the container and ran one of the bash scripts and it did start outputting binary data to standard out so I'm guessing these are working as expected.  Despite this, I am still getting scan results of failed.

**Comment by mclenburg** [comment]
Hi,
Port 8282 is for using the jalle-streamingproxy (https://github.com/Jalle19/node-ffmpeg-mpegts-proxy)  only. I guess, u don't use it, so the port has no meaning for you.

The error-messages seems to show, there is a program without any url in the json-response from pluto.tv-api. I've never seen that.

For using and importing xmltv-guide I've tried to give a possible way in issue 3. Maybe u can try this.

**Comment by mclenburg** [comment]
If scan of muxes is failing in tvheadend: can u post relating tvheadend-logline here?
I guess, failing scan of single mux is enough, though the error would be the same for all muxes, is it?

**Comment by mclenburg** [comment]
Closed with no more feedback
