### ISSUE TITLE
issue with getting playlist

### ISSUE THREAD

**Issue by Solution-TV** [mclenburg/plutoTV-tvheadend#7]
Hello

Just now i made install and im try to get playlist 
root@Ubuntu-1804-bionic-64-minimal ~/plutoTV-tvheadend-master # perl plutotv-generate.pl --createm3u
From 2021-02-17T20:29:10Z To 2021-02-27T20:29:10Z

How to add channel in tvhedend or where i can found playlist.m3u ?

Thank you

**Comment by mclenburg** [comment]
The m3u file is created in the same directory where the script was executed.
To include it in tvheadend, an Automatic IPTV Network has to be created as the source and the path to the m3u is entered as 
file:///home/..../plutotv.m3u as the URL.

**Comment by Solution-TV** [comment]
Hello

My server at Germany and script at /root/plutoTV-tvheadend-master/
after run script with this command perl plutotv-generate.pl --createm3u
about 10m i dont see inside directory playlist just i see script its doing xml file name plutotv-epg.xml and have all epg DE channel where the wrong why can not get plutotv.m3u ?

Thank you

**Comment by mclenburg** [comment]
Seems there's missing something.
The script prints out a Ready-Statement when finished working.
Pls provide full Script-Output and a list of all files in dir.
